package chatapp;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.URL;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Innocent
 */
public class Giris extends javax.swing.JFrame {

    
    private String exIP ;
    
    
    public Giris() {
        initComponents();
        btnGrup.add(rbServereBaglan);
        btnGrup.add(rbServerKur);
        btnGrupProtokol.add(rbTCP);
        btnGrupProtokol.add(rbUDP);
        
        pServerKur.setVisible(false);
        
        try {
            exIP = getExternalIP();
        } catch (IOException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        }
        setSize(400, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrup = new javax.swing.ButtonGroup();
        btnGrupProtokol = new javax.swing.ButtonGroup();
        rbServereBaglan = new javax.swing.JRadioButton();
        rbServerKur = new javax.swing.JRadioButton();
        pServereBaglan = new javax.swing.JPanel();
        txtIP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPortBaglan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBaglan = new javax.swing.JButton();
        pServerKur = new javax.swing.JPanel();
        txtPortKur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIP = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnKur = new javax.swing.JButton();
        lblExIP = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbTCP = new javax.swing.JRadioButton();
        rbUDP = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 200, 200));
        setResizable(false);

        rbServereBaglan.setSelected(true);
        rbServereBaglan.setText("Servere Bağlan");
        rbServereBaglan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbServereBaglanActionPerformed(evt);
            }
        });

        rbServerKur.setText("Server Kur");
        rbServerKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbServerKurActionPerformed(evt);
            }
        });

        jLabel1.setText("Server IP");

        jLabel2.setText("PORT");

        jLabel3.setBackground(new java.awt.Color(200, 200, 200));
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Bağlanamak istediğiniz Serverin IP ve Port numaralarını giriniz ");

        btnBaglan.setText("Bağlan");
        btnBaglan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaglanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pServereBaglanLayout = new javax.swing.GroupLayout(pServereBaglan);
        pServereBaglan.setLayout(pServereBaglanLayout);
        pServereBaglanLayout.setHorizontalGroup(
            pServereBaglanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pServereBaglanLayout.createSequentialGroup()
                .addGroup(pServereBaglanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pServereBaglanLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pServereBaglanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)
                        .addGroup(pServereBaglanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPortBaglan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pServereBaglanLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnBaglan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        pServereBaglanLayout.setVerticalGroup(
            pServereBaglanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pServereBaglanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(pServereBaglanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pServereBaglanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPortBaglan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBaglan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel4.setText("PORT");

        jLabel5.setText("LAN IP Adresiniz");

        lblIP.setBackground(new java.awt.Color(51, 255, 153));
        lblIP.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblIP.setForeground(new java.awt.Color(255, 0, 0));
        lblIP.setText("IP");

        jLabel7.setBackground(new java.awt.Color(200, 200, 200));
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("IP numaranız aşagıdaki gibidir. Bir Port numarası giriniz.");

        btnKur.setText("Kur");
        btnKur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurActionPerformed(evt);
            }
        });

        lblExIP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblExIP.setForeground(new java.awt.Color(0, 204, 0));
        lblExIP.setText("IP");

        jLabel8.setText("WANl IP Adresiniz");

        javax.swing.GroupLayout pServerKurLayout = new javax.swing.GroupLayout(pServerKur);
        pServerKur.setLayout(pServerKurLayout);
        pServerKurLayout.setHorizontalGroup(
            pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pServerKurLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGroup(pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pServerKurLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPortKur, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pServerKurLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblExIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(pServerKurLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnKur, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pServerKurLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pServerKurLayout.setVerticalGroup(
            pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pServerKurLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblIP))
                .addGap(18, 18, 18)
                .addGroup(pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPortKur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(btnKur, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pServerKurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExIP)
                    .addComponent(jLabel8))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        rbTCP.setSelected(true);
        rbTCP.setText("TCP");

        rbUDP.setText("UDP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pServereBaglan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pServerKur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTCP)
                    .addComponent(rbServereBaglan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbUDP)
                    .addComponent(rbServerKur, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTCP)
                    .addComponent(rbUDP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbServereBaglan)
                    .addComponent(rbServerKur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pServereBaglan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pServerKur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbServereBaglanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbServereBaglanActionPerformed
        pServerKur.setVisible(false);
        pServereBaglan.setVisible(true);
    }//GEN-LAST:event_rbServereBaglanActionPerformed

    private void rbServerKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbServerKurActionPerformed
        pServereBaglan.setVisible(false);
        pServerKur.setVisible(true);
        
        lblIP.setText(getIP());
        lblExIP.setText(exIP);
    }//GEN-LAST:event_rbServerKurActionPerformed

    private void btnKurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurActionPerformed
        
        if (rbTCP.isSelected()) {
            try {
                ServerTCP server = new ServerTCP(Integer.parseInt(txtPortKur.getText()));
                server.setVisible(true);
                server.baslat();

            } catch (IOException ex) {
                Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (rbUDP.isSelected()) {
            
                ServerUDP serverUDP = new ServerUDP(Integer.parseInt(txtPortKur.getText()));
                serverUDP.setVisible(true);
                try {
                    serverUDP.baslat();
                } catch (IOException ex) {
                    Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                
            
        }
            
    }//GEN-LAST:event_btnKurActionPerformed

    private void btnBaglanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaglanActionPerformed
        
        if (rbTCP.isSelected()) {
            ClientTCP client = new ClientTCP(txtIP.getText(), Integer.parseInt(txtPortBaglan.getText()));
            client.setVisible(true);
            try {
                client.baslat();
            } catch (IOException ex) {
                Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (rbUDP.isSelected()){
            ClientUDP clientUDP = new ClientUDP(txtIP.getText(),Integer.parseInt(txtPortBaglan.getText()));
            clientUDP.setVisible(true);
            
            try {
                clientUDP.baslat();
            } catch (IOException ex) {
                Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnBaglanActionPerformed

    private String getIP() {
        InetAddress inet;
        String ip = null;
        try {
            inet = InetAddress.getLocalHost();
            ip = inet.getHostAddress();
        } catch (UnknownHostException e) {
            System.err.println(e);
        }
        return ip;
    }
    
    private String getExternalIP() throws IOException{
        URL url = new URL("http://checkip.amazonaws.com");
        BufferedReader in = new BufferedReader(new InputStreamReader(url.openStream()));
        String ip = in.readLine();
        return ip;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaglan;
    private javax.swing.ButtonGroup btnGrup;
    private javax.swing.ButtonGroup btnGrupProtokol;
    private javax.swing.JButton btnKur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblExIP;
    private javax.swing.JLabel lblIP;
    private javax.swing.JPanel pServerKur;
    private javax.swing.JPanel pServereBaglan;
    private javax.swing.JRadioButton rbServerKur;
    private javax.swing.JRadioButton rbServereBaglan;
    private javax.swing.JRadioButton rbTCP;
    private javax.swing.JRadioButton rbUDP;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPortBaglan;
    private javax.swing.JTextField txtPortKur;
    // End of variables declaration//GEN-END:variables

    
}
