/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chatapp;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Innocent
 */
public class ServerUDP extends javax.swing.JFrame {

    String nick;
    int port;
    int portDiger;
    DatagramSocket serverSocket;
    
    DatagramPacket receivePacket ;
    DatagramPacket sendPacket;
    
    private InetAddress IPAddress;
    
    byte[] receiveData = new byte[1024];
    byte[] sendData = new byte[1024];
    
    
    
    /**
     * Creates new form ServerUDP
     */
    public ServerUDP() {
        initComponents();
    }

    public ServerUDP(int port){
        initComponents();
        this.port=port;
        nick = getNick();
        
        
    }
    public void baslat() throws IOException{
        
        serverSocket = new DatagramSocket(port);
        receivePacket = new DatagramPacket(receiveData, receiveData.length);
        
        
        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    try {
                        serverSocket.receive(receivePacket);
                        String gelenMesaj = new String(receivePacket.getData());
                        txtMesajlar.setText(txtMesajlar.getText()+"\n"+gelenMesaj);
                        IPAddress = receivePacket.getAddress();
                        portDiger = receivePacket.getPort();
                    } catch (IOException ex) {
                        Logger.getLogger(ServerUDP.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    
                    
                }
            }
        }).start();

        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSatir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMesajlar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtSatir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatirActionPerformed(evt);
            }
        });

        txtMesajlar.setEditable(false);
        txtMesajlar.setBackground(new java.awt.Color(204, 204, 204));
        txtMesajlar.setColumns(20);
        txtMesajlar.setRows(5);
        jScrollPane1.setViewportView(txtMesajlar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSatir, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSatir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSatirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatirActionPerformed
        
        String giden = nick + " ~~~ " + txtSatir.getText();
        sendData = giden.getBytes();
        sendPacket =  new DatagramPacket(sendData, sendData.length,IPAddress,portDiger);
        
        try {
            serverSocket.send(sendPacket);
        } catch (IOException ex) {
            Logger.getLogger(ServerUDP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        txtMesajlar.setText(txtMesajlar.getText()+"\n"+nick+" ~~~ "+txtSatir.getText());
        txtSatir.setText(null);
    }//GEN-LAST:event_txtSatirActionPerformed

    private String getNick() {
        return JOptionPane.showInputDialog(this,"Bir nick giriniz:","Nick",JOptionPane.PLAIN_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerUDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerUDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerUDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerUDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUDP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMesajlar;
    private javax.swing.JTextField txtSatir;
    // End of variables declaration//GEN-END:variables
}
